name: Worker - New victims notifier

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  worker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dbfs branch
        uses: actions/checkout@v2
        with:
          ref: dbfs

      - name: Copy dbfs data into /tmp/data
        run: |
          mkdir -p /tmp/data
          cp -r * /tmp/data

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy dbfs data into ./data
        run: |
          mv /tmp/data .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python src/victims_worker.py

      - name: Copy dbfs from ./data to .
        run: |
          mv ./data /tmp/

      - name: Checkout dbfs branch
        uses: actions/checkout@v2
        with:
          ref: dbfs

      - name: Copy dbfs data from /tmp/data to .
        run: |
          mv /tmp/data/* .

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add notified_victims.txt
          git commit -m "actions_run::Worker - New victims notifier"
          git push origin dbfs